[package]
name = "Test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
anyhow = "1.0.86"
tonlib = "0.17.1"
num-bigint = "0.4.6"
